[meta]
name = "Openplanet Store"
author = "NitroQuery"
category = "General"

# siteid = 103
version = "1.0.0-alpha.1"

# perms = "paid"

[game]
min_version = "2020-12-25"
# max_version = "2021-06-03"

[script]
imports = [
  "Icons.as",
  "Formatting.as",
  "Time.as"
]
