/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package opstore/src/opstore */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// PUBLIC API
// Since Go is a garbage collected language, and the garbage collector needs
// to know the location of every pointer to Go memory. Then Because of this
// Openlpanet Store API Should avoid exporting pointers.
// Initialize Openplanet Store
extern __declspec(dllexport) char* Initialize(char* path);

// GetPluginImagePath return path to plugin image.
// If local image does not exist then it tries to download
// requested image to local cache. When both fail
// then empty string is returned.
extern __declspec(dllexport) char* GetPluginImagePath(GoInt siteID);

// GetAvailablePlugins returns json string of
extern __declspec(dllexport) char* GetAvailablePlugins();

// Dispose performs graceful shutdown of Openplanet store
extern __declspec(dllexport) GoUint8 Dispose();

// DeletePlugin
extern __declspec(dllexport) char* DeletePlugin(GoInt pluginType, char* pluginPath);
extern __declspec(dllexport) char* DownloadPlugin(GoInt siteID, char* pluginFile);

#ifdef __cplusplus
}
#endif
